"""Add extended film fields from TMDB

Revision ID: 625b03c650e9
Revises: a1b2c3d4e5f6
Create Date: 2026-08-20 10:18:51.014939

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '625b03c650e9'
down_revision: Union[str, Sequence[str], None] = 'a1b2c3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('bookings_user_id_fkey'), 'bookings', type_='foreignkey')
    op.create_foreign_key(None, 'bookings', 'users', ['user_id'], ['id'])
    op.add_column('films', sa.Column('original_title', sa.String(), nullable=True))
    op.add_column('films', sa.Column('tagline', sa.String(), nullable=True))
    op.add_column('films', sa.Column('backdrop_url', sa.String(), nullable=True))
    op.add_column('films', sa.Column('trailer_url', sa.String(), nullable=True))
    op.add_column('films', sa.Column('original_language', sa.String(), nullable=True))
    op.add_column('films', sa.Column('spoken_languages', sa.ARRAY(sa.String()), nullable=True))
    op.add_column('films', sa.Column('production_countries', sa.ARRAY(sa.String()), nullable=True))
    op.add_column('films', sa.Column('production_companies', sa.ARRAY(sa.String()), nullable=True))
    op.add_column('films', sa.Column('runtime', sa.Integer(), nullable=True))
    op.add_column('films', sa.Column('status', sa.String(), nullable=True))
    op.add_column('films', sa.Column('adult', sa.Boolean(), nullable=True))
    op.add_column('films', sa.Column('imdb_id', sa.String(), nullable=True))
    op.add_column('films', sa.Column('homepage', sa.String(), nullable=True))
    op.add_column('films', sa.Column('budget', sa.Integer(), nullable=True))
    op.add_column('films', sa.Column('revenue', sa.Integer(), nullable=True))
    op.add_column('films', sa.Column('vote_average', sa.Float(), nullable=True))
    op.add_column('films', sa.Column('vote_count', sa.Integer(), nullable=True))
    op.add_column('films', sa.Column('popularity', sa.Float(), nullable=True))
    op.drop_column('films', 'duration_min')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('films', sa.Column('duration_min', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('films', 'popularity')
    op.drop_column('films', 'vote_count')
    op.drop_column('films', 'vote_average')
    op.drop_column('films', 'revenue')
    op.drop_column('films', 'budget')
    op.drop_column('films', 'homepage')
    op.drop_column('films', 'imdb_id')
    op.drop_column('films', 'adult')
    op.drop_column('films', 'status')
    op.drop_column('films', 'runtime')
    op.drop_column('films', 'production_companies')
    op.drop_column('films', 'production_countries')
    op.drop_column('films', 'spoken_languages')
    op.drop_column('films', 'original_language')
    op.drop_column('films', 'trailer_url')
    op.drop_column('films', 'backdrop_url')
    op.drop_column('films', 'tagline')
    op.drop_column('films', 'original_title')
    op.drop_constraint(None, 'bookings', type_='foreignkey')
    op.create_foreign_key(op.f('bookings_user_id_fkey'), 'bookings', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###
